services:
  db:
    image: postgres:16-alpine
    container_name: exampython_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-exampython}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty123}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-exampython}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
