# Generated by Django 6.0 on 2026-07-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_igridients_stockmovement_recipeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
