# Generated by Django 6.0 on 2026-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_profile_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igridients',
            name='unit',
            field=models.CharField(choices=[('g', 'грамм'), ('pcs', 'штук'), ('ml', 'миллилитров')], default='g', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
